### ISSUE TITLE
Add Blur efect

### ISSUE THREAD

**Issue by deinok** [pixelcog/parallax.js#113]
Add an option to add a blur efect in the image of the background like

data-image-blur="5"

-webkit-filter: blur(5px);
-moz-filter: blur(5px);
-o-filter: blur(5px);
-ms-filter: blur(5px);
filter: blur(5px);

**Comment by mikegreiling** [comment]
If a blur is desired, I think it would make more sense to just add it via css, as in:

```css
img.parallax-slider {
  -webkit-filter: blur(5px);
  -moz-filter: blur(5px);
  -o-filter: blur(5px);
  -ms-filter: blur(5px);
  filter: blur(5px);
}
```
