### ISSUE TITLE
Color overlay image not working on mobile

### ISSUE THREAD

**Issue by ner00** [pixelcog/parallax.js#231]
I tried to put color overlay on an image and it works fine on a desktop computer, but on a mobile device the color doesn't appear, it seems that it it gets under the image instead of over it. Any particular approach that would be universal or correct?

Here is an example of the style and code:
    
    .paralax{
        background-color: rgba(0,0,0,.6);
     }
`<div class="paralax" data-parallax="scroll" data-image-src="paralax_image.png"></div>`

**Comment by wstoettinger** [comment]
using a pseudo element with absolute positioning might help:

```css
.parallax::after {
    content: '';
    position: absolute;
    bottom: 0;
    left: 0;
    right: 0;
    top: 0;
    background-color: rgba(0,0,0,.6);
    pointer-events: none;
    z-index: 99;
}
```
