### ISSUE TITLE
Problem with parallax-slider div

### ISSUE THREAD

**Issue by yoran1998** [pixelcog/parallax.js#252]
Hi,
I am facing some issues when I try to put some text over de parallax image.
Without the <div class="parallax-slider> everything is working fine, but as soon as I put it there it shows just white on the page.
Do you see what I am doing wrong and help me?

This is my html
```html
<section class="home-section">
  <div class="parallax-home">
    <div class="parallax-slider">
      <span class="element" style="position:absolute; top:800px; left:800px;">Some text< /span>
    </div>
  </div>
</section>
```
My CSS
```css
.parallax-home {
  min-height: 800px;
  background: transparent;
}

.parallax-slider {
  min-height: 800px;
  background: transparent;
}
```

My Javascript
```javascript
$('.parallax-home').parallax({
      imageSrc: 'wp-content/themes/yoranvderve/dist/images/backgroundAfrika.jpg'});
```
Thanks
