### ISSUE TITLE
Same size for each element

### ISSUE THREAD

**Issue by morawcik** [pixelcog/parallax.js#259]
Hi

It's possible (even with manual change code) to make all parallax elements with the same height? I have couple of images and some of them are bigger than other and it's ugly when each one parallax has different height :(

**Comment by wstoettinger** [comment]
this should be possible setting a fixed height of the parallax window like so: 

```css
.parallax-window {
	height: 400px;
	background: transparent;
}
```

I may kindly ask you to use stackoverflow for questions like this in the future!
