### ISSUE TITLE
Possibility of fading in

### ISSUE THREAD

**Issue by developer2323** [pixelcog/parallax.js#31]
Would it be possible to implement a fade in animation on the loaded image?

**Comment by mikegreiling** [comment]
If you don't care about IE9 support, you could try CSS animations:

```css
img.parallax-slider {
    animation: fadein 2s;
}
@keyframes fadein {
    from { opacity: 0; }
    to   { opacity: 1; }
}
```

Or, you could use JavaScript:

```javascript
$(function() {
    // after parallax plugin is initialized...
    $('img.parallax-slider').hide().load(function() {
        $(this).fadeIn('slow');
    });
})
```

Note, you may need to fidget with these a bit. I haven't tested them, but this should get you started.
